### ISSUE TITLE
Case-sensitive command

### ISSUE THREAD

**Issue by Zaph-x** [Dendrobyte/OinkUtils#1]
In base command you have a case sensitive command on [this line](https://github.com/Mobkinz78/OinkUtils/blob/3b382a41199e4eaa1f938ea29a4e1a43e737dfc8/src/main/java/com/oinkcraft/oinkutils/BaseCommand.java#L18).

**Comment by Dendrobyte** [comment]
Doesn't do anything yet, lol, but good catch. Fixéd
